import { useCallback, useEffect, useState } from 'react'
import type { ReactNode } from 'react'
import { AlertTriangle, Banknote, Check, Code2, FileCheck2, KeyRound, Landmark, Network, RefreshCw, Scale, Send, ShieldAlert, Webhook } from 'lucide-react'
import { api } from '../lib/api'
import type { Role, SimulationStep } from '../types'
import { Tooltip } from './Tooltip'

type Item = Record<string, any>
const money = (value = 0) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'BRL' }).format(value / 100)
const readable = (value?: string) => value?.replaceAll('_', ' ') ?? '—'

function ActionTrace({ steps, onClose }: { steps: SimulationStep[]; onClose: () => void }) {
  return <div className="operation-trace"><header><strong>Operation completed safely</strong><button onClick={onClose}>Dismiss</button></header>{steps.map((step, index) => <div className={`trace-line ${step.status}`} key={`${step.key}-${index}`}><span><Check size={12}/></span><div><strong>{step.title}</strong><p>{step.detail}</p>{step.evidence && <code>{step.evidence}</code>}</div></div>)}</div>
}

function Empty({ text }: { text: string }) { return <div className="workspace-empty">{text}</div> }

export function RoleWorkspace({ role, refreshDashboard }: { role: Role; refreshDashboard: () => void | Promise<void> }) {
  const [data, setData] = useState<Item>({})
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')
  const [steps, setSteps] = useState<SimulationStep[]>([])
  const load = useCallback(async () => { setData(await api.workspace(role)) }, [role])
  useEffect(() => { void load() }, [load])
  const refreshWorkspace = async () => {
    setBusy(true); setMessage(''); setSteps([])
    try {
      await Promise.all([load(), Promise.resolve(refreshDashboard())])
      setMessage(`Workspace refreshed at ${new Date().toLocaleTimeString()}.`)
    } catch (error) {
      setMessage(error instanceof Error ? error.message : 'Workspace refresh failed')
    } finally {
      setBusy(false)
    }
  }
  const run = async (operation: () => Promise<Item>, success: string) => {
    setBusy(true); setMessage('')
    try { const result = await operation(); setSteps((result.steps as SimulationStep[]) ?? []); setMessage(result.secret ? `${success} One-time secret: ${result.secret}` : success); await load(); refreshDashboard() }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Operation failed') }
    finally { setBusy(false) }
  }

  if (role === 'merchant_owner') return <section className="role-workspace" id="workspace">
    <WorkspaceTitle icon={<Landmark/>} eyebrow="Merchant workspace" title="Business, funds and customer cases" text="Operate the complete merchant payment lifecycle. Every mutation exposes its safety trace and accounting consequence." onRefresh={refreshWorkspace} refreshing={busy}/>
    <div className="workspace-metrics"><Metric label="Available for settlement" value={money(data.available_balance)} tip="Derived from merchant-payable ledger credits minus debits; never maintained as an editable balance."/><Metric label="Authorized to capture" value={(data.authorized_payments as Item[] ?? []).length}/><Metric label="Open disputes" value={(data.disputes as Item[] ?? []).filter(x => !['won','lost'].includes(x.status)).length}/><Metric label="Settlements" value={(data.settlements as Item[] ?? []).length}/></div>
    <div className="workspace-columns"><WorkspacePanel title="Authorized payments" icon={<Banknote/>}>{(data.authorized_payments as Item[] ?? []).map(payment => <Row key={payment.id} title={payment.id} meta={`${money(payment.amount)} · ${payment.customer_reference}`} status={payment.status} actions={<button disabled={busy} onClick={() => run(() => api.capture(role, payment.id), 'Authorization captured and ledger posted.')}>Capture</button>}/>) }{!(data.authorized_payments as Item[] ?? []).length && <Empty text="Run a manual-capture or approved risk scenario to populate this queue."/>}</WorkspacePanel>
      <WorkspacePanel title="Settlements and payouts" icon={<Landmark/>}><div className="inline-create"><input id="settlement-amount" type="number" defaultValue="10000" aria-label="Settlement amount in centavos"/><button disabled={busy} onClick={() => { const input = document.getElementById('settlement-amount') as HTMLInputElement; void run(() => api.createSettlement(role, Number(input.value)), 'Funds reserved for settlement.') }}>Create settlement</button></div>{(data.settlements as Item[] ?? []).map(item => <Row key={item.id} title={item.id} meta={`${money(item.amount)} · ${item.bank_reference ?? 'Awaiting bank result'}`} status={item.status}/>)}</WorkspacePanel></div>
    <div className="workspace-columns"><WorkspacePanel title="Refundable payments" icon={<RefreshCw/>}>{(data.refundable_payments as Item[] ?? []).map(item => { const remaining = item.captured_amount - item.refunded_amount; return <Row key={item.id} title={item.id} meta={`${money(remaining)} refundable · ${item.customer_reference}`} status={item.status} actions={<button disabled={busy} onClick={() => run(() => api.refund(role, item.id, { amount: remaining, idempotency_key: `refund-${item.id}-${Date.now()}` }), 'Refund confirmed with a balanced reversing entry.')}>Refund remaining</button>}/> })}</WorkspacePanel><WorkspacePanel title="Disputes requiring merchant evidence" icon={<Scale/>}>{(data.disputes as Item[] ?? []).map(item => <Row key={item.id} title={`${readable(item.reason)} · ${money(item.amount)}`} meta={`Due ${new Date(item.due_at).toLocaleDateString()} · ${item.evidence.length} evidence item(s)`} status={item.status} actions={!['won','lost'].includes(item.status) ? <button disabled={busy} onClick={() => run(() => api.disputeAction(role, item.id, 'evidence', 'Order receipt and fulfillment confirmation uploaded by merchant.'), 'Evidence attached to dispute timeline.')}>Submit evidence</button> : undefined}/>)}</WorkspacePanel></div>
    <Feedback message={message} steps={steps} clear={() => { setMessage(''); setSteps([]) }}/>
  </section>

  if (role === 'merchant_developer') return <section className="role-workspace" id="workspace">
    <WorkspaceTitle icon={<Code2/>} eyebrow="Developer workspace" title="Integration control plane" text="Manage credentials, webhook endpoints, delivery attempts and recent execution traces without exposing stored secrets." onRefresh={refreshWorkspace} refreshing={busy}/>
    <div className="workspace-metrics"><Metric label="Active API keys" value={(data.api_keys as Item[] ?? []).filter(x => x.status === 'active').length}/><Metric label="Webhook endpoints" value={(data.webhook_endpoints as Item[] ?? []).length}/><Metric label="Retrying deliveries" value={(data.deliveries as Item[] ?? []).filter(x => x.status === 'retrying').length}/><Metric label="Recent request traces" value={(data.request_traces as Item[] ?? []).length}/></div>
    <div className="workspace-columns"><WorkspacePanel title="API keys" icon={<KeyRound/>}><div className="inline-create"><input id="key-name" defaultValue="Checkout service"/><button disabled={busy} onClick={() => { const input = document.getElementById('key-name') as HTMLInputElement; void run(() => api.createApiKey(role, input.value), 'API key created. Copy the one-time secret shown below.') }}>Create key</button></div>{(data.api_keys as Item[] ?? []).map(key => <Row key={key.id} title={key.name} meta={`•••• ${key.key_last4} · ${(key.scopes ?? []).join(', ')}`} status={key.status} actions={key.status === 'active' ? <button onClick={() => run(() => api.revokeApiKey(role, key.id), 'API key revoked immediately.')}>Revoke</button> : undefined}/>)}</WorkspacePanel>
      <WorkspacePanel title="Webhook endpoints" icon={<Webhook/>}><div className="inline-create"><input id="webhook-url" defaultValue="https://merchant.example/webhooks"/><button disabled={busy} onClick={() => { const input = document.getElementById('webhook-url') as HTMLInputElement; void run(() => api.createWebhook(role, input.value), 'Webhook endpoint and signing secret created.') }}>Add endpoint</button></div>{(data.webhook_endpoints as Item[] ?? []).map(endpoint => <Row key={endpoint.id} title={endpoint.url} meta={`Signing secret •••• ${endpoint.secret_last4}`} status={endpoint.enabled ? 'enabled' : 'disabled'}/>)}</WorkspacePanel></div>
    <WorkspacePanel title="Delivery attempts" icon={<Send/>}>{(data.deliveries as Item[] ?? []).map(item => <Row key={item.id} title={readable(item.event_type)} meta={`HTTP ${item.response_code ?? '—'} · ${item.attempts} attempt(s) · ${item.id}`} status={item.status} actions={item.status !== 'delivered' ? <button onClick={() => run(() => api.replayWebhook(role, item.id), 'Webhook redelivered with a fresh signature.')}>Replay</button> : undefined}/>)}</WorkspacePanel>
    <WorkspacePanel title="Recent execution traces" icon={<Code2/>}>{(data.request_traces as Item[] ?? []).map(item => <Row key={item.id} title={`${readable(item.scenario)} · ${item.payment_id ?? 'no payment'}`} meta={`${item.steps.length} safety steps · trace ${item.id}`} status={item.outcome}/>)}</WorkspacePanel>
    <SecretFeedback message={message} data={steps} clear={() => { setMessage(''); setSteps([]) }}/>
  </section>

  if (role === 'operations_admin') return <section className="role-workspace" id="workspace">
    <WorkspaceTitle icon={<Network/>} eyebrow="Operations command center" title="Infrastructure health and recovery" text="Control routing availability, resolve external inconsistencies and manage asynchronous financial operations." onRefresh={refreshWorkspace} refreshing={busy}/>
    <div className="workspace-metrics"><Metric label="Processors online" value={(data.processors as Item[] ?? []).filter(x => x.health !== 'offline').length}/><Metric label="Ambiguous payments" value={(data.recovery_queue as Item[] ?? []).length}/><Metric label="Open reconciliation" value={(data.reconciliation as Item[] ?? []).filter(x => x.status === 'open').length}/><Metric label="Pending outbox events" value={data.pending_outbox as number ?? 0}/></div>
    <WorkspacePanel title="Processor routing health" icon={<Network/>}>{(data.processors as Item[] ?? []).map(item => <Row key={item.id} title={item.display_name} meta={`${item.success_rate}% success · ${item.latency_ms} ms · ${item.fee_bps} bps`} status={item.health} actions={<select disabled={busy} value={item.health} onChange={event => run(() => api.processorHealth(role, item.id, event.target.value), `${item.display_name} routing state updated.`)}><option>healthy</option><option>degraded</option><option>offline</option></select>}/>)}</WorkspacePanel>
    <div className="workspace-columns"><WorkspacePanel title="Reconciliation exceptions" icon={<FileCheck2/>}>{(data.reconciliation as Item[] ?? []).map(item => <Row key={item.id} title={readable(item.case_type)} meta={`${item.processor} · Internal ${money(item.internal_amount)} / Processor ${money(item.processor_amount)}`} status={item.status} actions={item.status === 'open' ? <button onClick={() => run(() => api.resolveReconciliation(role, item.id, 'Processor report and internal reference verified.'), 'Reconciliation exception resolved.')}>Resolve</button> : undefined}/>)}</WorkspacePanel>
      <WorkspacePanel title="Settlement bank outcomes" icon={<Landmark/>}>{(data.settlements as Item[] ?? []).map(item => <Row key={item.id} title={item.id} meta={money(item.amount)} status={item.status} actions={item.status === 'pending' ? <><button onClick={() => run(() => api.settlementAction(role, item.id, 'complete'), 'Settlement completed and liability cleared.')}>Complete</button><button className="warn" onClick={() => run(() => api.settlementAction(role, item.id, 'fail'), 'Settlement moved to failed operations queue.')}>Fail</button></> : item.status === 'failed' ? <button onClick={() => run(() => api.settlementAction(role, item.id, 'retry'), 'Failed settlement safely resubmitted.')}>Retry</button> : undefined}/>)}</WorkspacePanel></div>
    <Feedback message={message} steps={steps} clear={() => { setMessage(''); setSteps([]) }}/>
  </section>

  if (role === 'risk_analyst') return <section className="role-workspace" id="workspace">
    <WorkspaceTitle icon={<ShieldAlert/>} eyebrow="Risk workspace" title="Explainable decisions and disputes" text="Review deterministic signals, approve or reject held authorizations, and resolve chargeback outcomes." onRefresh={refreshWorkspace} refreshing={busy}/>
    <div className="workspace-metrics"><Metric label="Pending reviews" value={(data.risk_cases as Item[] ?? []).filter(x => x.status === 'pending').length}/><Metric label="Enabled fraud rules" value={(data.fraud_rules as Item[] ?? []).filter(x => x.enabled).length}/><Metric label="Disputes under review" value={(data.disputes as Item[] ?? []).filter(x => !['won','lost'].includes(x.status)).length}/><Metric label="Highest pending score" value={Math.max(0, ...(data.risk_cases as Item[] ?? []).filter(x => x.status === 'pending').map(x => x.score))}/></div>
    <WorkspacePanel title="Manual review queue" icon={<ShieldAlert/>}>{(data.risk_cases as Item[] ?? []).map(item => <div className="risk-card" key={item.id}><div><span className="risk-score">{item.score}</span><div><strong>{item.payment_id}</strong><small>{item.signals.length} matched signals · {item.status}</small></div></div><ul>{item.signals.map((signal: string) => <li key={signal}>{signal}</li>)}</ul>{item.status === 'pending' && <div className="row-actions"><button onClick={() => run(() => api.riskDecision(role, item.id, 'approve', 'Signals reviewed; authorization may proceed to merchant capture.'), 'Risk case approved without automatically capturing funds.')}>Approve</button><button className="warn" onClick={() => run(() => api.riskDecision(role, item.id, 'reject', 'Risk exceeds the platform acceptance threshold.'), 'Risk case rejected and payment failed.')}>Reject</button></div>}</div>) }{!(data.risk_cases as Item[] ?? []).length && <Empty text="Run the High-risk review scenario to create a case."/>}</WorkspacePanel>
    <div className="workspace-columns"><WorkspacePanel title="Fraud rules" icon={<AlertTriangle/>}>{(data.fraud_rules as Item[] ?? []).map(item => <Row key={item.id} title={item.name} meta={`${readable(item.field)} ${readable(item.operator)} ${item.threshold}`} status={item.enabled ? item.action : 'disabled'} actions={<button onClick={() => run(() => api.toggleFraudRule(role, item.id), `Fraud rule ${item.enabled ? 'disabled' : 'enabled'}.`)}>{item.enabled ? 'Disable' : 'Enable'}</button>}/>)}</WorkspacePanel><WorkspacePanel title="Dispute outcomes" icon={<Scale/>}>{(data.disputes as Item[] ?? []).map(item => <Row key={item.id} title={`${readable(item.reason)} · ${money(item.amount)}`} meta={`${item.evidence.length} evidence item(s)`} status={item.status} actions={!['won','lost'].includes(item.status) ? <><button onClick={() => run(() => api.disputeAction(role, item.id, 'win', 'Merchant evidence accepted by simulated processor.'), 'Dispute won; reserved funds returned.')}>Mark won</button><button className="warn" onClick={() => run(() => api.disputeAction(role, item.id, 'lose', 'Evidence did not satisfy processor requirements.'), 'Dispute lost; chargeback liability posted.')}>Mark lost</button></> : undefined}/>)}</WorkspacePanel></div>
    <Feedback message={message} steps={steps} clear={() => { setMessage(''); setSteps([]) }}/>
  </section>

  const ledger = data.ledger_entries as Item[] ?? []
  const audits = data.audit_events as Item[] ?? []
  return <section className="role-workspace" id="workspace"><WorkspaceTitle icon={<Scale/>} eyebrow="Independent audit workspace" title="Trace every state change to accounting evidence" text="This perspective is entirely read-only. Inspect journal balance, transaction grouping and actor-attributed audit records." onRefresh={refreshWorkspace} refreshing={busy}/><div className="workspace-metrics"><Metric label="Visible debits" value={money(data.visible_debits)}/><Metric label="Visible credits" value={money(data.visible_credits)}/><Metric label="Integrity result" value={data.visible_balanced ? 'Balanced' : 'Exception'}/><Metric label="Audit events" value={audits.length}/></div><WorkspacePanel title="Immutable journal" icon={<Scale/>}>{ledger.slice(0, 30).map(item => <Row key={item.id} title={readable(item.account)} meta={`${item.transaction_id} · ${item.description}`} status={item.debit ? `Debit ${money(item.debit)}` : `Credit ${money(item.credit)}`}/>)}</WorkspacePanel><WorkspacePanel title="Actor-attributed audit trail" icon={<FileCheck2/>}>{audits.slice(0, 30).map(item => <Row key={item.id} title={readable(item.action)} meta={`${item.actor_role} · ${item.resource_type} ${item.resource_id}`} status={new Date(item.created_at).toLocaleString()}/>)}</WorkspacePanel><Feedback message={message} steps={steps} clear={() => { setMessage(''); setSteps([]) }}/></section>
}

function WorkspaceTitle({ icon, eyebrow, title, text, onRefresh, refreshing }: { icon: ReactNode; eyebrow: string; title: string; text: string; onRefresh: () => void | Promise<void>; refreshing: boolean }) { return <header className="workspace-title"><div className="workspace-title-icon">{icon}</div><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div><button className="icon-button" onClick={() => void onRefresh()} disabled={refreshing} aria-label={refreshing ? 'Refreshing workspace' : 'Refresh workspace'} title="Refresh workspace data"><RefreshCw className={refreshing ? 'spinning' : ''}/></button></header> }
function Metric({ label, value, tip }: { label: string; value: ReactNode; tip?: string }) { return <article><span>{label}{tip && <Tooltip text={tip}/>}</span><strong>{value}</strong></article> }
function WorkspacePanel({ title, icon, children }: { title: string; icon: ReactNode; children: ReactNode }) { return <article className="workspace-panel"><header><div>{icon}<h3>{title}</h3></div></header><div className="workspace-panel-body">{children}</div></article> }
function Row({ title, meta, status, actions }: { title: string; meta: string; status: string; actions?: ReactNode }) { return <div className="workspace-row"><div><strong>{title}</strong><small>{meta}</small></div><span className={`workspace-status ${status}`}>{readable(status)}</span>{actions && <div className="row-actions">{actions}</div>}</div> }
function Feedback({ message, steps, clear }: { message: string; steps: SimulationStep[]; clear: () => void }) { if (!message) return null; return <div className="workspace-feedback"><strong>{message}</strong>{steps.length > 0 && <ActionTrace steps={steps} onClose={clear}/>} {!steps.length && <button onClick={clear}>Dismiss</button>}</div> }
function SecretFeedback(props: { message: string; data: SimulationStep[]; clear: () => void }) { return <Feedback message={props.message} steps={props.data} clear={props.clear}/> }
